### ISSUE TITLE
Incompatible with ansible 1.8.3

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/tape#22]
```
TASK: [web | Check out FE application] ****************************************
fatal: [staging.bellwetherinsights.com] => error while evaluating conditional: fe_app

FATAL: all hosts have already failed -- aborting
```

**Comment by BrandonMathis** [comment]
Really crappy issue has been posted to [Ansible](https://github.com/ansible/ansible/issues/9962)

**Comment by leonelgalan** [comment]
`error while evaluating conditional: fe_app` its only because `"{{local_dir}}/site_vars.yml"` wasn't loaded as a var file in _omnibox.yml_. More details on: #20

**Comment by BrandonMathis** [comment]
Looks like it is being loaded as a var file to me

https://github.com/smashingboxes/smashing_boxer/blob/master/omnibox.yml#L7

**Comment by leonelgalan** [comment]
Well, that line exist, but the values are not there. `{{local_dir}}` has the correct value, but for some reason the variables aren't loaded. The error changes if you run everything rather than deploy, because it just crashes on the first variable it needs from site_vars.yml.

**Comment by leonelgalan** [comment]
Issue fixed with https://github.com/smashingboxes/tape/commit/e3d0251a8a646e28201967166e6f541652f19752
