### ISSUE TITLE
Install coffee-script

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/tape#27]
Install coffee-script npm package when you provision the server

**Comment by joeyjoejoejr** [comment]
On weaveup were using the front-end app's package.json to install things like this.  It might make sense to put a package.json in our rails projects for things like this as well.

**Comment by BrandonMathis** [comment]
I think that coffee-script is required by @btushinde's smashing-dev-tool which is then used to install a fe apps packages.

**Comment by BrandonMathis** [comment]
Moved to #29
