### ISSUE TITLE
Rename existing rolefiles so the hooks make sense

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/tape#28]
Names like app, app_server, web,  and database are not very explanatory.

I propose that we agree upon a new list of steps that the provisioning and deployment process undergo and then change the role names to reflect these steps.

**Comment by iandonovan** [comment]
`omnibox.yml` tackles the following sections, omitting the custom ones:

* `database`, which installs postgres. I propose we rename it to `postgres_setup`.
* `general`, which sets up the `deployer_user`, does the `apt-get update upgrade`, handles swapping, and installs several base packages (Vim, Git, etc.). I think this is too large a set of operations to name properly. Can we do away with the `general` name and just call its separate parts on their own? I propose calling those, respectively, `apt_update`, `configure_swap_file`, and `install_essentials`. Split it off into new roles.
* `web`, like `general`, also depends on `deployer_user`. It has the handler to restart nginx, plus it performs several nginx tasks and does some front-end installs/builds. I think we can break this into two parts. Take `web` and split it into two new roles, `nginx_setup` and `front_end_setup`.
* `legacy` handles rbenv, installing a new one and removing the old one if necessary. Therefore, I think it can be renamed to `rbenv_setup`.
* `gems`, big surprise, handles bundler and rbenv rehashing. I'd rename it to `bundle_environment_setup`.
* `app_server` does a ~ton~, largely revolving around Unicorn, dropping/creating/migrating/seeding the DB, waiting for server config files (e.g. `secrets.yml`), and even installing gems. I think it can be broken into three roles: `unicorn_setup` (for Unicorn, natch); `load_database`, and `rails_configs_setup`. Is it possible to move the `bundle install` command over to the `gems` role?
* `delayed_job`, obviously, configures Delayed Job. I think this is named just fine, but I think I want to stick with my theme of appending "_setup" to stuff and propose `delayed_job_setup`.

In sum, that means we'd move to having the following roles, (roughly) in order of their operation:
`postgres_setup`, `apt_update`, `configure_swap_file`, `install_essentials`, `nginx_setup`, `front_end_setup`, `rbenv_setup`, `bundle_environment_setup`, `unicorn_setup`, `load_database`, `rails_configs_setup_`, `delayed_job_setup`.

I'm also fine with (A) removing all the `_setup` garbage or (B) Moving it to the front, e.g. `set_up_rails_configs` or `load_database`.

**Comment by leonelgalan** [comment]
Thanks for the explanation on each role.

I think `database` (postgres) and `web` (nginx) names are pretty descriptive and inline with "roles" on other frameworks: capistrano used those names. I like how you broke `app_server`

`gems` could disappear. zzet.rbenv includes a [handler for `rbenv rehash`](https://github.com/zzet/ansible-rbenv-role/blob/master/handlers/main.yml) and a [default-gems](https://github.com/zzet/ansible-rbenv-role/blob/master/files/default-gems) file that installs _bundler_, what other gems do we need?

That said, my changes on https://github.com/smashingboxes/tape/issues/31 are not going to be finished today, so don't wait for me. I can help implementing this once we settle on the names.

**Comment by BrandonMathis** [comment]
I like this order/naming

* apt_update
* postgres
* configure_swap_file
* install_essentials
* nginx
* front_end
* rbenv
* bundle_environment
* unicorn
* load_database
* rails_configs
* delayed_job

**Comment by iandonovan** [comment]
I like your names a lot, @BrandonMathis. The `setup_` prefix was unnecessary.

**Comment by iandonovan** [comment]
Addressed in #37.
