### ISSUE TITLE
Stale Unicorn ID?

### ISSUE THREAD

**Issue by iandonovan** [smashingboxes/tape#44]
I don't know if this is exclusively a Tape thing or just a coincidence -- it doesn't happen consistently -- but I deployed a project just now and ran into some trouble restarting Unicorn. The tape task (`tape ansible restart_unicorn`) reported everything went a-okay, but the `unicorn.log` told a different story:

```python
lib/unicorn/http_server.rb:206:in `pid=': Already running on PID:30551 (or pid=/home/deployer/<project name redacted>/tmp/unicorn.pid is stale) (ArgumentError)
```

So Unicorn wasn't restarting because it was already running. I solved it by manually killing the unicorn processes on the server, then re-running the `tape ansible restart_unicorn` command. That worked fine.

So I suppose my question is, should we have a way for Tape to force the restart? Is that necessary, or should we strengthen the task somehow to ensure the unicorns are stopped before trying to restart them?

**Comment by BrandonMathis** [comment]
The upstart procedures for unicorn in tape are pretty buggy and needs a refactor.

**Comment by BrandonMathis** [comment]
I'm currently working on a fix for this.
