### ISSUE TITLE
Roles not getting installed by installer

### ISSUE THREAD

**Issue by reedlaw** [smashingboxes/tape#45]
After running the installer and then trying to run `tape ansible everything` I get the following error:

    ERROR: cannot find role in /home/reed/.gem/ruby/2.2.0/bundler/gems/tape-ef7f376ba652/roles/jnv.unattended-upgrades or /home/reed/.gem/ruby/2.2.0/bundler/gems/tape-ef7f376ba652/jnv.unattended-upgrades or /etc/ansible/roles/jnv.unattended-upgrades

**Comment by BrandonMathis** [comment]
What version of tape?

**Comment by reedlaw** [comment]
It was the version I cloned from this repo 5 days ago.

**Comment by BrandonMathis** [comment]
Pulling in @leonelgalan on this

There is a likely possibility that you did not run tape installer install. You always have to run tape installer install after you:

* add tape to your gemfile
* upgrade tape
* bundle install tape for the first time (even if it is already in the Gemfile.lock)

I propose that we either

* Install ansible galaxy roles to the roles/ directory inside the rails project repo
* Prompt the user that `tape installer install` has not been run

**Comment by leonelgalan** [comment]
By now tape changed too much, just re install. You could also look at the last commit on [0.3.1](https://github.com/smashingboxes/tape/tree/0.3.1) I added a dependency installer task and output everything to STDOUT, so we can see if there is an error.

**Comment by BrandonMathis** [comment]
Should we consider calling to `ansible-galaxy install` every time we run `tape ansible <action>`?

**Comment by BrandonMathis** [comment]
@reedlaw what do you have in your Gemfile?

**Comment by reedlaw** [comment]
@BrandonMathis I've already cleared tape out of that project. Like I said, it was the current github master as of 6 days ago. After installing it in a new project using the same method (i.e. adding `gem 'tape', github: 'smashingboxes/tape', group: :development` to my Gemfile) I get this version: `/home/reed/.gem/ruby/2.2.0/bundler/gems/tape-bed6fd3135fd`.

**Comment by reedlaw** [comment]
Now I get:
```ERROR: cannot find role in /home/reed/sb/actual_id/roles/leonelgalan.node or /home/reed/sb/actual_id/leonelgalan.node or /home/reed/sb/actual_id/roles/leonelgalan.node or /home/reed/.gem/ruby/2.2.0/bundler/gems/tape-bed6fd3135fd/roles/leonelgalan.node or /home/reed/.gem/ruby/2.2.0/bundler/gems/tape-bed6fd3135fd/vendor/leonelgalan.node```

**Comment by BrandonMathis** [comment]
what was the output from `tape installer install`?

**Comment by reedlaw** [comment]
All good. I saw the checkmarks next to each step.

**Comment by reedlaw** [comment]
This seems to be fixed now.
