### ISSUE TITLE
Need to be able to skip certain parts of the `everything` task

### ISSUE THREAD

**Issue by jrforrest** [smashingboxes/tape#5]
The use-case right now is just skipping rbenv stuff, but perhaps a mechanism for skipping more things would be good.

We could do this by exposing ansible tags to the user, but that makes our wrapper over ansible somewhat leaky.

**Comment by iandonovan** [comment]
@BrandonMathis @jrforrest What's the actionable on this issue? Can it be closed, just from its age?

**Comment by leonelgalan** [comment]
Better dependencies and good tagging is all we need, with that we can use --skip-tags=SKIP_TAGS. I think @jrforrest concern was how long some things take. Even when rbenv and Ruby are installed it still takes a while to go trough the tasks. We shouldn't run through those tags when deploying.

**Comment by leonelgalan** [comment]
I added an option to run only specific tasks #42: `-t Tag1,Tag2`

**Comment by BrandonMathis** [comment]
You can also just modify your playbook to only run roles you want.
