### ISSUE TITLE
I need a better name

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/tape#9]
Since this is mostly going to behave like a command like tool I'd like to change the name to something short and box/packing/shipping related.

* tape
* wrap
* pack

**Comment by BrandonMathis** [comment]
Anyone care about the name? I'm gonna change it to **tape** unless someone demands that I no

**Comment by iandonovan** [comment]
![smarf](https://cloud.githubusercontent.com/assets/1161474/5670624/a2273aa2-974f-11e4-89a1-636538f9de5f.png)

**Comment by joeyjoejoejr** [comment]
I'm good with tape.

**Comment by leonelgalan** [comment]
`tape` it is!

**Comment by joshvc** [comment]
Just out of curiosity, I checked rubygems, and someone's already got `tape`. https://rubygems.org/gems/tape

**Comment by leonelgalan** [comment]
I'm willing to surrender `packing_tape`, which was supposed to be packer and a `tape` of sorts. But it could all leave inside `packing_tape` the ansible recipes, playbook, the gem and the packer integration.
